### ISSUE TITLE
Some labels are missing ?

### ISSUE THREAD

**Issue by bonswouar** [marcelklehr/recognize#37]
I was playing with the code when I noticed some labels are missing in the yml, probably on purpose ?
For example :
```yml
pizza:
  threshold: 0.2
  categories:
    - food
 ```
With this example the result is that pizza images are tagged as "food" only.
Although I feel like most of these (pizza specially) should be tagged too, people tend to search for those, don't you think ?
